#
#Wed Jul 29 01:47:34 CST 2026
downloadedAt=Wed Jul 29 01\:47\:34 CST 2026
url=https\://raw.githubusercontent.com/GTNewHorizons/ExampleMod1.7.10/0.2.2/gtnhShared/spotless.eclipseformat.xml
version=1
